version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app


# outra maneira é:

# rodar o nest.js apenas com o node.js da máquina
# rodar o next.js apenas com o node.js da máquina
# rodar o mongodb com docker